### ISSUE TITLE
USER STORY: VIEWING: View Specific Product

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_5#10]
# DESCRIPTION
As a **user** I can **view a specific product** so that **I can identify the price, description and read the reviews**

# ACCEPTANCE CRITERIA
1. Be able to see the price
2. Be able to see the description
3. Be able to see reviews

# TASKS
- [x] Create the specific product view
- [x] Create the specific product template
- [x] Create the specific product url
- [x] Display the product's reviews
