### ISSUE TITLE
USER STORY: VIEWING: View Specific Blog Post

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_5#11]
# DESCRIPTION
As a **user** I can **view a specific blog post** so that **I can read the full content**

# ACCEPTANCE CRITERIA
1. Be able to read the blog post

# TASKS
- [x] Create specific blog post view
- [x] Create specific blog post template
- [x] Create specific blog post url
