### ISSUE TITLE
USER STORY: LOG IN / REGISTER: User Area

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_5#14]
# DESCRIPTION
As a **user** I can **access a user area** so that **I can check my details and past orders**

# ACCEPTANCE CRITERIA
1. Be able to check details
2. Be able to check old orders

# TASKS
- [x] Create user area template
- [x] Add user info
- [x] Add user previous orders
