### ISSUE TITLE
USER STORY: SORT & SEARCH: Search

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_5#15]
# DESCRIPTION
As a **user** I can **search for specific keywords** so that **I can find specific products and blogs based on a specific keyword**

# ACCEPTANCE CRITERIA
1. Be able to sort for a specific keyword
2. Be able to see a list with the results

# TASKS
- [x] Add a search form
- [x] Create a specific view to handle the search function
- [x] Create a search template to display the results
- [x] Create a search url
