### ISSUE TITLE
USER STORY: CHECKOUT: Payment

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_5#16]
# DESCRIPTION
As a **user** I can **make a card payment** so that **I can finalize my purchase**

# ACCEPTANCE CRITERIA
1. Be able to make a payment

# TASKS
- [x] Set up Stripe
- [x] Create checkout view
- [x] Create checkout template
- [x] Create checkout url
- [x] Create checkout functions
