### ISSUE TITLE
USER STORY: ADMIN: Products

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_5#17]
# DESCRIPTION
As an **admin** I can **create, edit and delete products** so that **I can better manage the store**

# ACCEPTANCE CRITERIA
1. Be able to create a product
2. Be able to edit a product
3. Be able to delete a product

# TASKS
- [x] Create a product form
- [x] Create a admin view
- [x] Create a admin template
- [x] Create a admin url
