### ISSUE TITLE
USER STORY: ADMIN: Reviews

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_5#19]
# DESCRIPTION
As an **admin** I can **approve reviews** so that **I can control inappropriate content**

# ACCEPTANCE CRITERIA
1. Be able to check reviews to be approved
2. Approve reviews

# TASKS
- [x] Create a admin view
- [x] Create a admin template
- [x] Create a admin urls
