### ISSUE TITLE
USER STORY: VIEWING: List Of Products

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_5#8]
# DESCRIPTION
As a **user** I can **see all the products on a page** so that **I can decide what product I want to check**

# ACCEPTANCE CRITERIA
1. Be able to see all the products on the page
2. Be able to sort the products
3. Be able to filter the products

# TASKS
- [x] Create the products list view
- [x] Create the products list template
- [x] Create the products list urls
- [x] Add the functions to sort and filter the products
