### ISSUE TITLE
USER STORY: VIEWING: List Of Blogs Posts

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_5#9]
# DESCRIPTION
As a **user** I can **see a list with blog posts** so that **I can decide what I want to read**

# ACCEPTANCE CRITERIA
1. Be able to see a list with all the blog posts
2. Be able to select the post that I want to read

# TASKS
- [x] Create the blog list view
- [x] Create the blog list template
- [x] Create the blog list urls
